name: deploy to ec2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean bootJar

    - name: Generate deployment package
      run: |
        mkdir -p before-deploy
        cp scripts/*.sh before-deploy/
        cp appspec.yml before-deploy/
        cp build/libs/*.jar before-deploy/
        cd before-deploy && zip -r before-deploy *
        cd ../ && mkdir -p deploy
        mv before-deploy/before-deploy.zip deploy/fruit-mall.zip
      shell: bash

    - name: Make zip file
      run: zip -r ./fruit-mall.zip .
      shell: bash

    - name: Deliver to AWS S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: aws s3 cp ./deploy/fruit-mall.zip s3://fruit-mall-s3/jar-folder/

    - name: Code Deploy
      run: |
        aws deploy create-deployment \
        --application-name fruit-mall-codedeploy \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --deployment-group-name fruit-mall-codedeploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=fruit-mall-s3,bundleType=zip,key=jar-folder/fruit-mall.zip \
        --region us-east-1